@startuml lightSubsystem

namespace lightSubsystem {

    class BeamsEnum {
        - DippedBeams = 1
        - HighBeams = 2
    }
    note right of BeamsEnum
       Výčtová třída pro hlavní světla 
       (potkávací/dálková)
    end note

    class Indicator {
        - direction: DirectionEnum|None
        - warning: bool
        ---
        - __indicatorPeriod: Period
        - indicatorLight: bool|None
        + __init__(): None
        + update(): None                   
        + isLeft(): bool
        + isRight(): bool
    }
    note left of Indicator
        Třída ukládající stav "blikání" indikátorů (směrovek)

        <b>direction</b> - směr indikátoru (směrovek) nebo None
            ze stavoveho automatu (nebo hlavniho programu) se nastavuje takto:
            robot.lightsControl.indicator.direction = DirectionEnum::RIGHT
        <b>warning</b> - True pokud je aktivovany výstražný trojúhelník
            ze stavoveho automatu (nebo hlavniho programu) se nastavuje takto:
            robot.lightsControl.indicator.warning = True

        <b>__indicatorPeriod</b> - časovač, řídící změnu indicatorLight s timeoutem 400ms
        <b>indicatorLight</b> - stav blinkrů
            None - nemají blikat
            True - blikají     a právě teď svítí
            False - blikají    a právě teď jsou zhasnuté

        <b>update</b> - aktualizuj stav blinkru až bude čas
        
        <b>isLeft</b> - má blikat levý blinkr (tedy direction je LEFT nebo warning je True)
        <b>isRight</b> - má blikat pravý blinkr (tedy direction je RIGHT nebo warning je True)
    end note
    
    class LightsControl {
        - main: BeamsEnum
        - indicator: Indicator
        ---
        - __showPeriod: Period
        - __neopixels: NeoPixel
        - __velocity: velocity
        - __oldForward: float
        - __brakeTimer: Timer
        + __init__(velocity:Velocity): None
        + __setBrakeFromVelocity(): None
        + __isBrake(): bool  
        + __isReverse(): bool
        + __setColorIndicator(): None  
        + __setColorOtherLights(): None   
        + update(): None
        + __showColor(): None
        + __setColorToOneLed(ledNo:int, color:list[int]): None 
        + __setColor(ledList:list[int], color:list[int]): None
    }
    note left of LightsControl
        Třída starající se o všechny světla autíčka.

        <b>main</b> - hlavní světla (výčet z potkávací, dálková. None = vypnuto)
            musí se aktivovat ručně. Při inicializaci robota nebo v budoucnu podle okolního osvětlení.
        <b>indicator</b> - objekt směrovek (uvnitř se nastavují property direction a warning)
           směrovky už nejsou aktivované z velocity automaticky, musí se aktivovat ručně ze stavového automatu

        při záporné rychlosti se automaticky aktivuje zpáteční světlo (dokud velocity ukazuje zápornou rychlost)
        při zastavení (brždění) se automaticky aktivuje brzdové světlo (na 600ms) podle nastavení timeout v __brakeTimer

        <b>update</b> - aktualizuj stavy všeho v světelném susbsytému. A pokud je potřeba, změn barvy na všech ledkách
            nastavení barev a odeslání na ledky je aktivováno časovačem __showPeriod (každých 100ms)
        
        <b>_</b><b>_setBrakeFromVelocity</b> - spustí časovač __brakeTimer, pokud se zabrzdilo = dříve se jelo a teď právě ne
        <b>_</b><b>_isBrake</b> - má svítit brzdové světlo? (to jest je spuštěný __brakeTimer a jestě nevypršel jeho čas)
        <b>_</b><b>_setColorIndicator</b> - nastav barvu blinkrových světel podle nastavení v objektu Indicator
        <b>_</b><b>_setColorOtherLights</b> - nastav barvy předních a zadních světel (ne blinkrů) včetně brzdového a couvacího světla

        <b>_</b><b>_showColor</b> - nastav barvy všech světel a odešli je na ledky

        <b>_</b><b>_setColorToOneLed</b> - umí nastavit jednu barvu na jedno světlo
        <b>_</b><b>_setColor</b> - umí nastavit jednu barvu na více světel najednou
    end note

    Indicator -down-> timer.Period
    Indicator -right-> direction.DirectionEnum
    LightsControl -up-> Indicator
    LightsControl -right-> BeamsEnum
    LightsControl -up-> velocity.Velocity
    LightsControl -up-> timer.Period
    LightsControl -up-> timer.Timer
}

@enduml